export * from './business-controller.service';
import { BusinessControllerService } from './business-controller.service';
export * from './business-controller.serviceInterface';
export * from './business-type-controller.service';
import { BusinessTypeControllerService } from './business-type-controller.service';
export * from './business-type-controller.serviceInterface';
export * from './service-category-controller.service';
import { ServiceCategoryControllerService } from './service-category-controller.service';
export * from './service-category-controller.serviceInterface';
export * from './service-subcategory-controller.service';
import { ServiceSubcategoryControllerService } from './service-subcategory-controller.service';
export * from './service-subcategory-controller.serviceInterface';
export * from './service-template-controller.service';
import { ServiceTemplateControllerService } from './service-template-controller.service';
export * from './service-template-controller.serviceInterface';
export * from './user-controller.service';
import { UserControllerService } from './user-controller.service';
export * from './user-controller.serviceInterface';
export * from './zakazime-application.service';
import { ZakazimeApplicationService } from './zakazime-application.service';
export * from './zakazime-application.serviceInterface';
export const APIS = [BusinessControllerService, BusinessTypeControllerService, ServiceCategoryControllerService, ServiceSubcategoryControllerService, ServiceTemplateControllerService, UserControllerService, ZakazimeApplicationService];
