/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Business } from '../model/models';
import { CreateBusinessProfileRequest } from '../model/models';
import { CreateServiceRequest } from '../model/models';
import { MessageResponse } from '../model/models';
import { Service } from '../model/models';
import { UpdateServiceRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BusinessControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param businessId 
     * @param createServiceRequest 
     */
    addServiceToBusiness(businessId: number, createServiceRequest: CreateServiceRequest, extraHttpRequestParams?: any): Observable<MessageResponse>;

    /**
     * 
     * 
     * @param businessId 
     * @param createServiceRequest 
     */
    addServicesToBusiness(businessId: number, createServiceRequest: Array<CreateServiceRequest>, extraHttpRequestParams?: any): Observable<MessageResponse>;

    /**
     * 
     * 
     * @param createBusinessProfileRequest 
     */
    createBusinessProfile(createBusinessProfileRequest: CreateBusinessProfileRequest, extraHttpRequestParams?: any): Observable<Business>;

    /**
     * 
     * 
     */
    getAllBusinesses(extraHttpRequestParams?: any): Observable<Array<Business>>;

    /**
     * 
     * 
     * @param businessId 
     */
    getBusinessProfile(businessId: number, extraHttpRequestParams?: any): Observable<Business>;

    /**
     * 
     * 
     */
    getBusinessProfileForUser(extraHttpRequestParams?: any): Observable<Business>;

    /**
     * 
     * 
     * @param businessId 
     */
    getServicesOfBusiness(businessId: number, extraHttpRequestParams?: any): Observable<Array<Service>>;

    /**
     * 
     * 
     * @param businessId 
     * @param serviceId 
     * @param updateServiceRequest 
     */
    updateService(businessId: number, serviceId: number, updateServiceRequest: UpdateServiceRequest, extraHttpRequestParams?: any): Observable<MessageResponse>;

}
