/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateServiceSubcategoryRequest } from '../model/models';
import { MessageResponse } from '../model/models';
import { ServiceSubcategory } from '../model/models';
import { UpdateServiceSubcategoryRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ServiceSubcategoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<MessageResponse>;

    /**
     * 
     * 
     * @param createServiceSubcategoryRequest 
     */
    create(createServiceSubcategoryRequest: CreateServiceSubcategoryRequest, extraHttpRequestParams?: any): Observable<ServiceSubcategory>;

    /**
     * 
     * 
     * @param id 
     */
    get(id: number, extraHttpRequestParams?: any): Observable<ServiceSubcategory>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<ServiceSubcategory>>;

    /**
     * 
     * 
     * @param id 
     * @param updateServiceSubcategoryRequest 
     */
    update(id: number, updateServiceSubcategoryRequest: UpdateServiceSubcategoryRequest, extraHttpRequestParams?: any): Observable<ServiceSubcategory>;

}
