/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateServiceCategoryRequest } from '../model/models';
import { MessageResponse } from '../model/models';
import { ServiceCategory } from '../model/models';
import { UpdateServiceCategoryRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ServiceCategoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createServiceCategoryRequest 
     */
    create1(createServiceCategoryRequest: CreateServiceCategoryRequest, extraHttpRequestParams?: any): Observable<ServiceCategory>;

    /**
     * 
     * 
     * @param id 
     */
    delete1(id: number, extraHttpRequestParams?: any): Observable<MessageResponse>;

    /**
     * 
     * 
     * @param id 
     */
    get1(id: number, extraHttpRequestParams?: any): Observable<ServiceCategory>;

    /**
     * 
     * 
     */
    getAll1(extraHttpRequestParams?: any): Observable<Array<ServiceCategory>>;

    /**
     * 
     * 
     * @param id 
     * @param updateServiceCategoryRequest 
     */
    update1(id: number, updateServiceCategoryRequest: UpdateServiceCategoryRequest, extraHttpRequestParams?: any): Observable<ServiceCategory>;

}
