/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Account } from '../model/models';
import { RegistrationRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    login(extraHttpRequestParams?: any): Observable<Account>;

    /**
     * 
     * 
     * @param registrationRequest 
     */
    registerUser(registrationRequest: RegistrationRequest, extraHttpRequestParams?: any): Observable<Account>;

}
