/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Business { 
    id?: number;
    typeId?: number;
    status?: string;
    name?: string;
    phoneNumber?: string;
    city?: string;
    postalCode?: string;
    address?: string;
    description?: string;
    createdOn?: string;
    updatedOn?: string;
}

